### ISSUE TITLE
Check Validity of Dates 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/Resume-Generator#10]
Currently we are able to select the start and end date for the users experience , education etc however there is no validation present in the routes in case the end date is before the start date which needs to be fixed .

Validate the dates provided by user and add checks for multiple validations.

**Comment by importhuman** [comment]
Hello! I haven't looked at the code yet, but I would like to contribute to this issue, and then more issues if possible.

**Comment by DiptoChakrabarty** [comment]
> Hello! I haven't looked at the code yet, but I would like to contribute to this issue, and then more issues if possible.

Please go ahead @importhuman

**Comment by importhuman** [comment]
Thank you!

**Comment by importhuman** [comment]
![Screenshot from 2020-09-26 17-09-37](https://user-images.githubusercontent.com/69148722/94339928-714e3580-001b-11eb-9f90-33750312fb51.png)
I am unable to run the app. I have searched online [here](https://stackoverflow.com/questions/33738467/how-do-i-know-if-i-can-disable-sqlalchemy-track-modifications/33790196#33790196) and done this in the ```test.py``` file:
```python
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
```

I have tried giving a False value as well. Please assist. I have tried removing the curly brackets in the .env file as well, if that is relevant.

**Comment by DiptoChakrabarty** [comment]
> ![Screenshot from 2020-09-26 17-09-37](https://user-images.githubusercontent.com/69148722/94339928-714e3580-001b-11eb-9f90-33750312fb51.png)
> I am unable to run the app. I have searched online [here](https://stackoverflow.com/questions/33738467/how-do-i-know-if-i-can-disable-sqlalchemy-track-modifications/33790196#33790196) and done this in the `test.py` file:
> 
> ```python
> app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
> ```
> 
> I have tried giving a False value as well. Please assist. I have tried removing the curly brackets in the .env file as well, if that is relevant.

@importhuman  the app seems to be running fine this is just a warning that setting SQLALCHEMY_TRACK_MODIFICATIONS as True will require extra memory and this is a common warning which comes every time you run  , this will not effect the overall running of the application , if you head over to http://localhost:5000 you should see the application has started there .

**Comment by importhuman** [comment]
I didn't realize I had to click on the link to proceed, will see now. 

Despite the .env file, we still have to sign up/log in, and the .env values still open the link even if the details are wrong.

**Comment by DiptoChakrabarty** [comment]
The env file values are for the mail service we are using within the application , the email used in the env is the mail through which the application users will receive emails in case they forgot password.
Login and registration is independent of those values .

**Comment by importhuman** [comment]
What is the password for then? 
For the issue, I'm trying to add some sort of validation in ```forms.py```.

**Comment by DiptoChakrabarty** [comment]
The password is your gmail account (through which you will send emails) password , since we need to authenticate  ourselves when we need to send emails using flask mail.
These values are only used when you send emails  that is in the forgot password route .

**Comment by importhuman** [comment]
The date validity is for education, experience and project fields, correct?

**Comment by DiptoChakrabarty** [comment]
yes for those three
