### ISSUE TITLE
Login form styling is off

### ISSUE THREAD

**Issue by devcshort** [DiptoChakrabarty/Resume-Generator#12]
Currently the form looks like below
![image](https://user-images.githubusercontent.com/13677134/94183409-3d2a1780-fe57-11ea-929c-58926fbb09d7.png)

However, I believe it should look like this
![image](https://user-images.githubusercontent.com/13677134/94183374-2daace80-fe57-11ea-9f97-865ad6e46f6f.png)

I'm willing to make a PR with the required changes, however I wanted to ask a question first as I'm not familiar with Flask. The lines in question look like this within the html template
```
<div class="form-check">
    {{ form.remember(class="form-check-input") }}
    {{ form.remember.label(class="form-check-input") }}
</div>
```

Does the label have to be generated using these template filters? Or can I change this to something like this?
```
<div class="form-check">
    <label class="form-check-input">
        {{ form.remember(class="form-check-input") }}
        Remember Me
    </label>
</div>
```
Don't want to go astray from best practices with the framework, so want to check before I start making changes.

**Comment by DiptoChakrabarty** [comment]
@devcshort    The labels are specified  in the forms.py file inside the resume folder , we are using a flask module called wtforms where we are creating a python classes which will represent our forms  .

 The labels can be changed to what you have specified but doing it like this would  mean repeating the label definitions in both places and not using the full advantages of the Flask Forms  , we could  use the jinja template method to define the labels in the html pages instead of hard coding it but nonetheless this looks more like a CSS issue and the way of defining the labels should not affect it   .

**Comment by devcshort** [comment]
Yeah, I could still make the related change using css. I've always preferred wrapping labels around the inputs so that the entire label and input box are clickable to check/uncheck the box, but not a requirement. I'll check this out 👍

**Comment by devcshort** [comment]
If it's alright with you, I can do this once hacktoberfest starts

**Comment by DiptoChakrabarty** [comment]
> If it's alright with you, I can do this once hacktoberfest starts

Sure no issue

**Comment by Lilykhan786** [comment]
Hi, can I help with improving the UI?

**Comment by DiptoChakrabarty** [comment]
Hi @Lilykhan786  , @devcshort seems to working on this one (I am assuming you are talking about the login form only) you can take another issue  if you want

**Comment by devcshort** [comment]
@DiptoChakrabarty can you assign this issue to me? Until it's assigned, it will still show up in the Hacktoberfest issue search

**Comment by devcshort** [comment]
@DiptoChakrabarty do you know if this project works on Windows PCs? I've tried running the steps in the README and have not been able to get it to work. Install always fails when installing requirements.txt I've updated Python, Pip, and setuptools, but still not working.

**Comment by DiptoChakrabarty** [comment]
@devcshort  it should work , in windows we have to use pip as far as I know , can you post the error or make a new issue and I will try to resolve it

**Comment by prasunbhunia** [comment]
hey, login form styling is off issue is open?

**Comment by prasunbhunia** [comment]
can you assign this issue to me? I have fixed this issue

![Screenshot (217)](https://user-images.githubusercontent.com/65885986/95716925-d0ea4900-0c89-11eb-8c50-588555e44d70.png)

**Comment by devcshort** [comment]
This issue can be reassigned. I was never able to get the project to work on my machine unfortunately. I have however already completed all my hacktoberfest PRs, so I won’t be too bummed if this gets reassigned to someone who has managed to get things working properly.

________________________________
