### ISSUE TITLE
Documentation errors (installation)

### ISSUE THREAD

**Issue by importhuman** [DiptoChakrabarty/Resume-Generator#14]
I noticed some discrepancies in the installation part of the README.md file:

- ```git clone https://github.com/DiptoChakrabarty/website``` Although it says "website", the link still works, but "Resume-Generator" might be better in the end.
- There is no directory named ```website``` in the repository. This seems to be a renaming issue, as with point 1. 
- Point 4 has a typo, it should be ```rm resume/site.db```.
- In point 5, the following can be excluded from the coding block:
```create file .env inside folder resume```
```Add the following ```

**Comment by DiptoChakrabarty** [comment]
yes there are documentation errors  in the ReadME it seems thanks for pointing it out @importhuman

**Comment by importhuman** [comment]
Have created a pull request with the suggested changes.

**Comment by importhuman** [comment]
Have closed earlier PR as it should be ```cd Resume-Generator```, will fix and submit again.
