### ISSUE TITLE
return status codes 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/Resume-Generator#6]
Some of the routes are not handling status codes efficiently , return relevant status codes for the routes

**Comment by ShubhamPalriwala** [comment]
Hey, Can I take this issue up ?

**Comment by DiptoChakrabarty** [comment]
> Hey, Can I take this issue up ?

Sure @ShubhamPalriwala

**Comment by ShubhamPalriwala** [comment]
Please check the PR #23 regarding this issue !
